RANDOM_LOWER_LIMIT = 1
RANDOM_UPPER_LIMIT = 1.001

WHALE_MULT = 1.01
WHALE_LOWER_MULT = 1.005
WHALE_UPPER_MULT = 1.015

BTCUSD_DECIMAL_PLACES = 5
TEN_THOUSAND = 10_000
DATE_FORMAT = "%Y-%m-%d %H:%M:%S"

CONFIG_FILE = "config.json"
LOGS = "logs"
BAR = "bar"
SHOW = "show"
MULTI = "multi"
LONG = "long"
HTML = ".html"
QTY_MAX_DEC = 6
FORMAT_STR = "%Y-%m-%d"

SECONDS_IN_1DAY = 86400
MINUTES_IN_1DAY = 1440
HOURS_IN_1DAY = 24
DAYS_IN_1DAY = 1

VOLATILE_PROB = 10_000
VOLATILE_PERIOD_MIN = 100
VOLATILE_PERIOD_MAX = 500

DATA_PATH = "data"
